apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- define "opensearch.fullname" -}}
{{- printf "%s-opensearch" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end }}
