package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"

	"github.com/acme/ticket-service/internal/repository"
)

// FindTicketByID is the resolver for the findTicketByID field.
func (r *entityResolver) FindTicketByID(ctx context.Context, id string) (*Ticket, error) {
	t, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrTicketNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("findTicketByID: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
