// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateTicketInput struct {
	Title      string            `json:"title"`
	Price      int               `json:"price"`
	Quota      int               `json:"quota"`
	MaxPerUser *int              `json:"maxPerUser,omitempty"`
	TicketType TicketType        `json:"ticketType"`
	Category   *TicketCategory   `json:"category,omitempty"`
	Event      *TicketEventInput `json:"event"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type SavedEventConnection struct {
	Edges    []*SavedEventEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type SavedEventEdge struct {
	Node   *Ticket `json:"node"`
	Cursor string  `json:"cursor"`
}

type SeatingPlan struct {
	ID string `json:"id"`
}

func (SeatingPlan) IsEntity() {}

type Ticket struct {
	ID           string         `json:"id"`
	Title        string         `json:"title"`
	Price        int            `json:"price"`
	PriceDecimal string         `json:"priceDecimal"`
	UserID       string         `json:"userId"`
	OrderID      *string        `json:"orderId,omitempty"`
	Quota        int            `json:"quota"`
	Reserved     int            `json:"reserved"`
	Sold         int            `json:"sold"`
	Available    int            `json:"available"`
	MaxPerUser   *int           `json:"maxPerUser,omitempty"`
	TicketType   TicketType     `json:"ticketType"`
	Category     TicketCategory `json:"category"`
	SeatingPlan  *SeatingPlan   `json:"seatingPlan,omitempty"`
	Event        *TicketEvent   `json:"event,omitempty"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
	SavedByMe    bool           `json:"savedByMe"`
}

func (Ticket) IsEntity() {}

type TicketConnection struct {
	Edges    []*TicketEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type TicketEdge struct {
	Node   *Ticket `json:"node"`
	Cursor string  `json:"cursor"`
}

type TicketEvent struct {
	Title        string  `json:"title"`
	Description  *string `json:"description,omitempty"`
	StartsAt     string  `json:"startsAt"`
	EndsAt       *string `json:"endsAt,omitempty"`
	ImageURL     *string `json:"imageUrl,omitempty"`
	VenueName    *string `json:"venueName,omitempty"`
	VenueAddress *string `json:"venueAddress,omitempty"`
}

type TicketEventInput struct {
	Title        *string `json:"title,omitempty"`
	Description  *string `json:"description,omitempty"`
	StartsAt     string  `json:"startsAt"`
	EndsAt       *string `json:"endsAt,omitempty"`
	ImageURL     *string `json:"imageUrl,omitempty"`
	VenueName    *string `json:"venueName,omitempty"`
	VenueAddress *string `json:"venueAddress,omitempty"`
}

type TicketFilter struct {
	AvailableOnly *bool           `json:"availableOnly,omitempty"`
	TicketType    *TicketType     `json:"ticketType,omitempty"`
	Search        *string         `json:"search,omitempty"`
	Category      *TicketCategory `json:"category,omitempty"`
	MinPrice      *int            `json:"minPrice,omitempty"`
	MaxPrice      *int            `json:"maxPrice,omitempty"`
}

type UpdateTicketInput struct {
	Title         *string           `json:"title,omitempty"`
	Price         *int              `json:"price,omitempty"`
	Quota         *int              `json:"quota,omitempty"`
	MaxPerUser    *int              `json:"maxPerUser,omitempty"`
	Event         *TicketEventInput `json:"event,omitempty"`
	SeatingPlanID *string           `json:"seatingPlanId,omitempty"`
}

type TicketCategory string

const (
	TicketCategoryConcert  TicketCategory = "CONCERT"
	TicketCategorySports   TicketCategory = "SPORTS"
	TicketCategoryComedy   TicketCategory = "COMEDY"
	TicketCategoryTheatre  TicketCategory = "THEATRE"
	TicketCategoryFestival TicketCategory = "FESTIVAL"
	TicketCategoryOther    TicketCategory = "OTHER"
)

var AllTicketCategory = []TicketCategory{
	TicketCategoryConcert,
	TicketCategorySports,
	TicketCategoryComedy,
	TicketCategoryTheatre,
	TicketCategoryFestival,
	TicketCategoryOther,
}

func (e TicketCategory) IsValid() bool {
	switch e {
	case TicketCategoryConcert, TicketCategorySports, TicketCategoryComedy, TicketCategoryTheatre, TicketCategoryFestival, TicketCategoryOther:
		return true
	}
	return false
}

func (e TicketCategory) String() string {
	return string(e)
}

func (e *TicketCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketCategory", str)
	}
	return nil
}

func (e TicketCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TicketType string

const (
	TicketTypeGeneralAdmission TicketType = "GENERAL_ADMISSION"
	TicketTypeSeated           TicketType = "SEATED"
)

var AllTicketType = []TicketType{
	TicketTypeGeneralAdmission,
	TicketTypeSeated,
}

func (e TicketType) IsValid() bool {
	switch e {
	case TicketTypeGeneralAdmission, TicketTypeSeated:
		return true
	}
	return false
}

func (e TicketType) String() string {
	return string(e)
}

func (e *TicketType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketType", str)
	}
	return nil
}

func (e TicketType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
