// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateTicketInput struct {
	Title      string     `json:"title"`
	Price      int        `json:"price"`
	Quota      int        `json:"quota"`
	MaxPerUser *int       `json:"maxPerUser,omitempty"`
	TicketType TicketType `json:"ticketType"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type SeatingPlan struct {
	ID string `json:"id"`
}

func (SeatingPlan) IsEntity() {}

type Ticket struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Price       int          `json:"price"`
	Quota       int          `json:"quota"`
	Available   int          `json:"available"`
	MaxPerUser  *int         `json:"maxPerUser,omitempty"`
	TicketType  TicketType   `json:"ticketType"`
	SeatingPlan *SeatingPlan `json:"seatingPlan,omitempty"`
	CreatedAt   string       `json:"createdAt"`
	UpdatedAt   string       `json:"updatedAt"`
}

func (Ticket) IsEntity() {}

type TicketConnection struct {
	Edges    []*TicketEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type TicketEdge struct {
	Node   *Ticket `json:"node"`
	Cursor string  `json:"cursor"`
}

type TicketFilter struct {
	AvailableOnly *bool       `json:"availableOnly,omitempty"`
	TicketType    *TicketType `json:"ticketType,omitempty"`
}

type UpdateTicketInput struct {
	Title      *string `json:"title,omitempty"`
	Price      *int    `json:"price,omitempty"`
	Quota      *int    `json:"quota,omitempty"`
	MaxPerUser *int    `json:"maxPerUser,omitempty"`
}

type TicketType string

const (
	TicketTypeGeneralAdmission TicketType = "GENERAL_ADMISSION"
	TicketTypeSeated           TicketType = "SEATED"
)

var AllTicketType = []TicketType{
	TicketTypeGeneralAdmission,
	TicketTypeSeated,
}

func (e TicketType) IsValid() bool {
	switch e {
	case TicketTypeGeneralAdmission, TicketTypeSeated:
		return true
	}
	return false
}

func (e TicketType) String() string {
	return string(e)
}

func (e *TicketType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketType", str)
	}
	return nil
}

func (e TicketType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
