package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"math"
	"strconv"
	"time"

	"github.com/acme/ticket-service/internal/repository"
	"github.com/acme/ticket-service/internal/service"
)

func intPriceToDecimalString(price int) string {
	value := float64(price) / 100.0
	return strconv.FormatFloat(math.Round(value*100)/100, 'f', 2, 64)
}

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input CreateTicketInput) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("createTicket: unauthorized: user identity required")
	}
	price := intPriceToDecimalString(input.Price)

	svcInput := service.CreateTicketInput{
		Title: input.Title,
		Price: price,
		Quota: input.Quota,
		UserID: userID,
	}
	if input.MaxPerUser != nil {
		svcInput.MaxPerUser = *input.MaxPerUser
	}
	if input.Event != nil {
		ev, err := mapEventInput(input.Event)
		if err != nil {
			return nil, fmt.Errorf("createTicket: %w", err)
		}
		svcInput.Event = ev
	}

	t, err := r.TicketService.CreateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("createTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, id string, input UpdateTicketInput) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("updateTicket: unauthorized: user identity required")
	}
	// Fetch the current ticket so we can fill fields the caller didn't change.
	existing, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}

	svcInput := service.UpdateTicketInput{
		ID:    id,
		Title: existing.Title,
		Price: existing.Price,
		UserID: userID,
	}

	if input.Title != nil {
		svcInput.Title = *input.Title
	}
	if input.Price != nil {
		svcInput.Price = intPriceToDecimalString(*input.Price)
	}
	if input.Event != nil {
		ev, err := mapEventInput(input.Event)
		if err != nil {
			return nil, fmt.Errorf("updateTicket: %w", err)
		}
		svcInput.Event = ev
	}

	t, err := r.TicketService.UpdateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// mapEventInput converts the GraphQL TicketEventInput to the repository TicketEvent.
func mapEventInput(in *TicketEventInput) (*repository.TicketEvent, error) {
	startsAt, err := time.Parse(time.RFC3339, in.StartsAt)
	if err != nil {
		return nil, fmt.Errorf("invalid startsAt %q: %w", in.StartsAt, err)
	}
	ev := &repository.TicketEvent{StartsAt: startsAt}
	if in.Title != nil {
		ev.Title = *in.Title
	}
	if in.Description != nil {
		ev.Description = *in.Description
	}
	if in.EndsAt != nil {
		t, err := time.Parse(time.RFC3339, *in.EndsAt)
		if err != nil {
			return nil, fmt.Errorf("invalid endsAt %q: %w", *in.EndsAt, err)
		}
		ev.EndsAt = &t
	}
	if in.ImageURL != nil {
		ev.ImageURL = *in.ImageURL
	}
	if in.VenueName != nil {
		ev.VenueName = *in.VenueName
	}
	if in.VenueAddress != nil {
		ev.VenueAddress = *in.VenueAddress
	}
	return ev, nil
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context) ([]*Ticket, error) {
	tickets, err := r.TicketService.ListTickets(ctx, repository.PaginationParams{})
	if err != nil {
		return nil, fmt.Errorf("tickets: %w", err)
	}
	result := make([]*Ticket, len(tickets))
	for i, t := range tickets {
		result[i] = mapTicketToGQL(t)
	}
	return result, nil
}

// TicketsConnection is the resolver for the ticketsConnection field.
func (r *queryResolver) TicketsConnection(ctx context.Context, filter *TicketFilter, first *int, after *string) (*TicketConnection, error) {
	limit := 20
	if first != nil && *first > 0 {
		limit = *first
	}
	if limit > 100 {
		limit = 100
	}

	params := repository.PaginationParams{Limit: limit + 1}
	if after != nil {
		params.After = *after
	}
	if filter != nil && filter.AvailableOnly != nil {
		params.AvailableOnly = *filter.AvailableOnly
	}

	tickets, err := r.TicketService.ListTickets(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("ticketsConnection: %w", err)
	}

	// Apply ticketType filter in-memory (repo doesn't accept it yet).
	if filter != nil && filter.TicketType != nil {
		filtered := tickets[:0]
		for _, t := range tickets {
			if string(t.TicketType) == string(*filter.TicketType) {
				filtered = append(filtered, t)
			}
		}
		tickets = filtered
	}

	hasNext := len(tickets) > limit
	if hasNext {
		tickets = tickets[:limit]
	}

	edges := make([]*TicketEdge, len(tickets))
	for i, t := range tickets {
		edges[i] = &TicketEdge{
			Node:   mapTicketToGQL(t),
			Cursor: fmt.Sprintf("%d:%s", t.CreatedAt.UnixMilli(), t.ID),
		}
	}

	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}

	return &TicketConnection{
		Edges:    edges,
		PageInfo: &PageInfo{HasNextPage: hasNext, EndCursor: endCursor},
	}, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*Ticket, error) {
	t, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrTicketNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("ticket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
