package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"

	"github.com/acme/ticket-service/internal/repository"
	"github.com/acme/ticket-service/internal/service"
)

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input CreateTicketInput) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("createTicket: unauthorized: user identity required")
	}
	price := intPriceToDecimalString(input.Price)

	svcInput := service.CreateTicketInput{
		Title:  input.Title,
		Price:  price,
		Quota:  input.Quota,
		UserID: userID,
	}
	if input.MaxPerUser != nil {
		svcInput.MaxPerUser = *input.MaxPerUser
	}
	if input.Event != nil {
		ev, err := mapEventInput(input.Event)
		if err != nil {
			return nil, fmt.Errorf("createTicket: %w", err)
		}
		svcInput.Event = ev
	}

	t, err := r.TicketService.CreateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("createTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, id string, input UpdateTicketInput) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("updateTicket: unauthorized: user identity required")
	}
	// Fetch the current ticket so we can fill fields the caller didn't change.
	existing, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}

	svcInput := service.UpdateTicketInput{
		ID:     id,
		Title:  existing.Title,
		Price:  existing.Price,
		UserID: userID,
	}

	if input.Title != nil {
		svcInput.Title = *input.Title
	}
	if input.Price != nil {
		svcInput.Price = intPriceToDecimalString(*input.Price)
	}
	if input.Event != nil {
		ev, err := mapEventInput(input.Event)
		if err != nil {
			return nil, fmt.Errorf("updateTicket: %w", err)
		}
		svcInput.Event = ev
	}
	if input.SeatingPlanID != nil {
		svcInput.SeatingPlanID = *input.SeatingPlanID
	}

	t, err := r.TicketService.UpdateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// SaveEvent is the resolver for the saveEvent field.
func (r *mutationResolver) SaveEvent(ctx context.Context, eventID string) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("saveEvent: unauthorized: user identity required")
	}
	ticket, err := r.TicketService.SaveEvent(ctx, userID, eventID)
	if err != nil {
		return nil, fmt.Errorf("saveEvent: %w", err)
	}
	t := mapTicketToGQL(ticket)
	t.SavedByMe = true
	return t, nil
}

// UnsaveEvent is the resolver for the unsaveEvent field.
func (r *mutationResolver) UnsaveEvent(ctx context.Context, eventID string) (*Ticket, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("unsaveEvent: unauthorized: user identity required")
	}
	if err := r.TicketService.UnsaveEvent(ctx, userID, eventID); err != nil {
		return nil, fmt.Errorf("unsaveEvent: %w", err)
	}
	ticket, err := r.TicketService.GetTicketByID(ctx, eventID)
	if err != nil {
		return nil, fmt.Errorf("unsaveEvent fetch: %w", err)
	}
	t := mapTicketToGQL(ticket)
	t.SavedByMe = false
	return t, nil
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context) ([]*Ticket, error) {
	tickets, err := r.TicketService.ListTickets(ctx, repository.PaginationParams{})
	if err != nil {
		return nil, fmt.Errorf("tickets: %w", err)
	}
	result := make([]*Ticket, len(tickets))
	for i, t := range tickets {
		result[i] = mapTicketToGQL(t)
	}
	return result, nil
}

// TicketsConnection is the resolver for the ticketsConnection field.
func (r *queryResolver) TicketsConnection(ctx context.Context, filter *TicketFilter, first *int, after *string) (*TicketConnection, error) {
	limit := 20
	if first != nil && *first > 0 {
		limit = *first
	}
	if limit > 100 {
		limit = 100
	}

	params := repository.PaginationParams{Limit: limit + 1}
	if after != nil {
		params.After = *after
	}
	if filter != nil && filter.AvailableOnly != nil {
		params.AvailableOnly = *filter.AvailableOnly
	}

	tickets, err := r.TicketService.ListTickets(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("ticketsConnection: %w", err)
	}

	// Apply ticketType filter in-memory (repo doesn't accept it yet).
	if filter != nil && filter.TicketType != nil {
		filtered := tickets[:0]
		for _, t := range tickets {
			if string(t.TicketType) == string(*filter.TicketType) {
				filtered = append(filtered, t)
			}
		}
		tickets = filtered
	}

	hasNext := len(tickets) > limit
	if hasNext {
		tickets = tickets[:limit]
	}

	edges := make([]*TicketEdge, len(tickets))
	for i, t := range tickets {
		edges[i] = &TicketEdge{
			Node:   mapTicketToGQL(t),
			Cursor: fmt.Sprintf("%d:%s", t.CreatedAt.UnixMilli(), t.ID),
		}
	}

	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}

	return &TicketConnection{
		Edges:    edges,
		PageInfo: &PageInfo{HasNextPage: hasNext, EndCursor: endCursor},
	}, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*Ticket, error) {
	t, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrTicketNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("ticket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// SavedEvents is the resolver for the savedEvents field.
func (r *queryResolver) SavedEvents(ctx context.Context, first *int, after *string) (*SavedEventConnection, error) {
	userID := userIDFromContext(ctx)
	if userID == "" {
		return nil, fmt.Errorf("savedEvents: unauthorized: user identity required")
	}
	limit := 20
	if first != nil && *first > 0 {
		limit = *first
	}
	var cursor string
	if after != nil {
		cursor = *after
	}
	tickets, err := r.TicketService.ListSavedEvents(ctx, userID, cursor, limit+1)
	if err != nil {
		return nil, fmt.Errorf("savedEvents: %w", err)
	}
	hasNextPage := len(tickets) > limit
	if hasNextPage {
		tickets = tickets[:limit]
	}
	edges := make([]*SavedEventEdge, len(tickets))
	for i, t := range tickets {
		gqlTicket := mapTicketToGQL(t)
		gqlTicket.SavedByMe = true
		edges[i] = &SavedEventEdge{
			Node:   gqlTicket,
			Cursor: t.ID,
		}
	}
	var endCursor *string
	if len(edges) > 0 {
		c := edges[len(edges)-1].Cursor
		endCursor = &c
	}
	return &SavedEventConnection{
		Edges: edges,
		PageInfo: &PageInfo{
			HasNextPage: hasNextPage,
			EndCursor:   endCursor,
		},
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
