package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/acme/ticket-service/internal/repository"
	"github.com/acme/ticket-service/internal/service"
)

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, input CreateTicketInput) (*Ticket, error) {
	price := strconv.Itoa(input.Price)

	// TicketType is not in service.CreateTicketInput — type is set via AttachSeatingPlan.
	svcInput := service.CreateTicketInput{
		Title: input.Title,
		Price: price,
		Quota: input.Quota,
	}
	if input.MaxPerUser != nil {
		svcInput.MaxPerUser = *input.MaxPerUser
	}

	t, err := r.TicketService.CreateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("createTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// UpdateTicket is the resolver for the updateTicket field.
func (r *mutationResolver) UpdateTicket(ctx context.Context, id string, input UpdateTicketInput) (*Ticket, error) {
	// Fetch the current ticket so we can fill fields the caller didn't change.
	existing, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}

	svcInput := service.UpdateTicketInput{
		ID:    id,
		Title: existing.Title,
		Price: existing.Price,
	}

	if input.Title != nil {
		svcInput.Title = *input.Title
	}
	if input.Price != nil {
		svcInput.Price = strconv.Itoa(*input.Price)
	}

	t, err := r.TicketService.UpdateTicket(ctx, svcInput)
	if err != nil {
		return nil, fmt.Errorf("updateTicket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// Tickets is the resolver for the tickets field.
func (r *queryResolver) Tickets(ctx context.Context) ([]*Ticket, error) {
	tickets, err := r.TicketService.ListTickets(ctx, repository.PaginationParams{})
	if err != nil {
		return nil, fmt.Errorf("tickets: %w", err)
	}
	result := make([]*Ticket, len(tickets))
	for i, t := range tickets {
		result[i] = mapTicketToGQL(t)
	}
	return result, nil
}

// Ticket is the resolver for the ticket field.
func (r *queryResolver) Ticket(ctx context.Context, id string) (*Ticket, error) {
	t, err := r.TicketService.GetTicketByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrTicketNotFound) {
			return nil, nil
		}
		return nil, fmt.Errorf("ticket: %w", err)
	}
	return mapTicketToGQL(t), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
