// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: venue/v1/venue.proto

package venuev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VenueService_ReserveHeldSeats_FullMethodName        = "/acme.venue.v1.VenueService/ReserveHeldSeats"
	VenueService_AutoAssignAndReserve_FullMethodName    = "/acme.venue.v1.VenueService/AutoAssignAndReserve"
	VenueService_ReleaseSeatReservation_FullMethodName  = "/acme.venue.v1.VenueService/ReleaseSeatReservation"
	VenueService_FinalizeSeatReservation_FullMethodName = "/acme.venue.v1.VenueService/FinalizeSeatReservation"
	VenueService_GetSeatingPlan_FullMethodName          = "/acme.venue.v1.VenueService/GetSeatingPlan"
)

// VenueServiceClient is the client API for VenueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VenueServiceClient interface {
	ReserveHeldSeats(ctx context.Context, in *ReserveHeldSeatsRequest, opts ...grpc.CallOption) (*ReserveHeldSeatsResponse, error)
	AutoAssignAndReserve(ctx context.Context, in *AutoAssignAndReserveRequest, opts ...grpc.CallOption) (*AutoAssignAndReserveResponse, error)
	ReleaseSeatReservation(ctx context.Context, in *ReleaseSeatReservationRequest, opts ...grpc.CallOption) (*ReleaseSeatReservationResponse, error)
	FinalizeSeatReservation(ctx context.Context, in *FinalizeSeatReservationRequest, opts ...grpc.CallOption) (*FinalizeSeatReservationResponse, error)
	GetSeatingPlan(ctx context.Context, in *GetSeatingPlanRequest, opts ...grpc.CallOption) (*GetSeatingPlanResponse, error)
}

type venueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVenueServiceClient(cc grpc.ClientConnInterface) VenueServiceClient {
	return &venueServiceClient{cc}
}

func (c *venueServiceClient) ReserveHeldSeats(ctx context.Context, in *ReserveHeldSeatsRequest, opts ...grpc.CallOption) (*ReserveHeldSeatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveHeldSeatsResponse)
	err := c.cc.Invoke(ctx, VenueService_ReserveHeldSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) AutoAssignAndReserve(ctx context.Context, in *AutoAssignAndReserveRequest, opts ...grpc.CallOption) (*AutoAssignAndReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoAssignAndReserveResponse)
	err := c.cc.Invoke(ctx, VenueService_AutoAssignAndReserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) ReleaseSeatReservation(ctx context.Context, in *ReleaseSeatReservationRequest, opts ...grpc.CallOption) (*ReleaseSeatReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSeatReservationResponse)
	err := c.cc.Invoke(ctx, VenueService_ReleaseSeatReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) FinalizeSeatReservation(ctx context.Context, in *FinalizeSeatReservationRequest, opts ...grpc.CallOption) (*FinalizeSeatReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeSeatReservationResponse)
	err := c.cc.Invoke(ctx, VenueService_FinalizeSeatReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueServiceClient) GetSeatingPlan(ctx context.Context, in *GetSeatingPlanRequest, opts ...grpc.CallOption) (*GetSeatingPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeatingPlanResponse)
	err := c.cc.Invoke(ctx, VenueService_GetSeatingPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VenueServiceServer is the server API for VenueService service.
// All implementations should embed UnimplementedVenueServiceServer
// for forward compatibility.
type VenueServiceServer interface {
	ReserveHeldSeats(context.Context, *ReserveHeldSeatsRequest) (*ReserveHeldSeatsResponse, error)
	AutoAssignAndReserve(context.Context, *AutoAssignAndReserveRequest) (*AutoAssignAndReserveResponse, error)
	ReleaseSeatReservation(context.Context, *ReleaseSeatReservationRequest) (*ReleaseSeatReservationResponse, error)
	FinalizeSeatReservation(context.Context, *FinalizeSeatReservationRequest) (*FinalizeSeatReservationResponse, error)
	GetSeatingPlan(context.Context, *GetSeatingPlanRequest) (*GetSeatingPlanResponse, error)
}

// UnimplementedVenueServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVenueServiceServer struct{}

func (UnimplementedVenueServiceServer) ReserveHeldSeats(context.Context, *ReserveHeldSeatsRequest) (*ReserveHeldSeatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveHeldSeats not implemented")
}
func (UnimplementedVenueServiceServer) AutoAssignAndReserve(context.Context, *AutoAssignAndReserveRequest) (*AutoAssignAndReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoAssignAndReserve not implemented")
}
func (UnimplementedVenueServiceServer) ReleaseSeatReservation(context.Context, *ReleaseSeatReservationRequest) (*ReleaseSeatReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeatReservation not implemented")
}
func (UnimplementedVenueServiceServer) FinalizeSeatReservation(context.Context, *FinalizeSeatReservationRequest) (*FinalizeSeatReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeSeatReservation not implemented")
}
func (UnimplementedVenueServiceServer) GetSeatingPlan(context.Context, *GetSeatingPlanRequest) (*GetSeatingPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatingPlan not implemented")
}
func (UnimplementedVenueServiceServer) testEmbeddedByValue() {}

// UnsafeVenueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VenueServiceServer will
// result in compilation errors.
type UnsafeVenueServiceServer interface {
	mustEmbedUnimplementedVenueServiceServer()
}

func RegisterVenueServiceServer(s grpc.ServiceRegistrar, srv VenueServiceServer) {
	// If the following call panics, it indicates UnimplementedVenueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VenueService_ServiceDesc, srv)
}

func _VenueService_ReserveHeldSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveHeldSeatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ReserveHeldSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ReserveHeldSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ReserveHeldSeats(ctx, req.(*ReserveHeldSeatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_AutoAssignAndReserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoAssignAndReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).AutoAssignAndReserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_AutoAssignAndReserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).AutoAssignAndReserve(ctx, req.(*AutoAssignAndReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_ReleaseSeatReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSeatReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).ReleaseSeatReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_ReleaseSeatReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).ReleaseSeatReservation(ctx, req.(*ReleaseSeatReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_FinalizeSeatReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeSeatReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).FinalizeSeatReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_FinalizeSeatReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).FinalizeSeatReservation(ctx, req.(*FinalizeSeatReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueService_GetSeatingPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeatingPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueServiceServer).GetSeatingPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VenueService_GetSeatingPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueServiceServer).GetSeatingPlan(ctx, req.(*GetSeatingPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VenueService_ServiceDesc is the grpc.ServiceDesc for VenueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VenueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.venue.v1.VenueService",
	HandlerType: (*VenueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveHeldSeats",
			Handler:    _VenueService_ReserveHeldSeats_Handler,
		},
		{
			MethodName: "AutoAssignAndReserve",
			Handler:    _VenueService_AutoAssignAndReserve_Handler,
		},
		{
			MethodName: "ReleaseSeatReservation",
			Handler:    _VenueService_ReleaseSeatReservation_Handler,
		},
		{
			MethodName: "FinalizeSeatReservation",
			Handler:    _VenueService_FinalizeSeatReservation_Handler,
		},
		{
			MethodName: "GetSeatingPlan",
			Handler:    _VenueService_GetSeatingPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "venue/v1/venue.proto",
}
