// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: venue/v1/venue.proto

package venuev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SeatDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeatId        string                 `protobuf:"bytes,1,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,2,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	SeatLabel     string                 `protobuf:"bytes,3,opt,name=seat_label,json=seatLabel,proto3" json:"seat_label,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatDetail) Reset() {
	*x = SeatDetail{}
	mi := &file_venue_v1_venue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatDetail) ProtoMessage() {}

func (x *SeatDetail) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatDetail.ProtoReflect.Descriptor instead.
func (*SeatDetail) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{0}
}

func (x *SeatDetail) GetSeatId() string {
	if x != nil {
		return x.SeatId
	}
	return ""
}

func (x *SeatDetail) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *SeatDetail) GetSeatLabel() string {
	if x != nil {
		return x.SeatLabel
	}
	return ""
}

func (x *SeatDetail) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

type ReserveHeldSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SeatIds       []string               `protobuf:"bytes,5,rep,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveHeldSeatsRequest) Reset() {
	*x = ReserveHeldSeatsRequest{}
	mi := &file_venue_v1_venue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveHeldSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveHeldSeatsRequest) ProtoMessage() {}

func (x *ReserveHeldSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveHeldSeatsRequest.ProtoReflect.Descriptor instead.
func (*ReserveHeldSeatsRequest) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveHeldSeatsRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *ReserveHeldSeatsRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ReserveHeldSeatsRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveHeldSeatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveHeldSeatsRequest) GetSeatIds() []string {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *ReserveHeldSeatsRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ReserveHeldSeatsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId      string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Seats              []*SeatDetail          `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	UnavailableSeatIds []string               `protobuf:"bytes,4,rep,name=unavailable_seat_ids,json=unavailableSeatIds,proto3" json:"unavailable_seat_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReserveHeldSeatsResponse) Reset() {
	*x = ReserveHeldSeatsResponse{}
	mi := &file_venue_v1_venue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveHeldSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveHeldSeatsResponse) ProtoMessage() {}

func (x *ReserveHeldSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveHeldSeatsResponse.ProtoReflect.Descriptor instead.
func (*ReserveHeldSeatsResponse) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveHeldSeatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveHeldSeatsResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveHeldSeatsResponse) GetSeats() []*SeatDetail {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *ReserveHeldSeatsResponse) GetUnavailableSeatIds() []string {
	if x != nil {
		return x.UnavailableSeatIds
	}
	return nil
}

type AutoAssignAndReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	SectionId     string                 `protobuf:"bytes,3,opt,name=section_id,json=sectionId,proto3" json:"section_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,4,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoAssignAndReserveRequest) Reset() {
	*x = AutoAssignAndReserveRequest{}
	mi := &file_venue_v1_venue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoAssignAndReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoAssignAndReserveRequest) ProtoMessage() {}

func (x *AutoAssignAndReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoAssignAndReserveRequest.ProtoReflect.Descriptor instead.
func (*AutoAssignAndReserveRequest) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{3}
}

func (x *AutoAssignAndReserveRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *AutoAssignAndReserveRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *AutoAssignAndReserveRequest) GetSectionId() string {
	if x != nil {
		return x.SectionId
	}
	return ""
}

func (x *AutoAssignAndReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *AutoAssignAndReserveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AutoAssignAndReserveRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AutoAssignAndReserveRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type AutoAssignAndReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Seats         []*SeatDetail          `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoAssignAndReserveResponse) Reset() {
	*x = AutoAssignAndReserveResponse{}
	mi := &file_venue_v1_venue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoAssignAndReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoAssignAndReserveResponse) ProtoMessage() {}

func (x *AutoAssignAndReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoAssignAndReserveResponse.ProtoReflect.Descriptor instead.
func (*AutoAssignAndReserveResponse) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{4}
}

func (x *AutoAssignAndReserveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AutoAssignAndReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *AutoAssignAndReserveResponse) GetSeats() []*SeatDetail {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ReleaseSeatReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // CANCELLED | EXPIRED | COMPENSATION
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatReservationRequest) Reset() {
	*x = ReleaseSeatReservationRequest{}
	mi := &file_venue_v1_venue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatReservationRequest) ProtoMessage() {}

func (x *ReleaseSeatReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSeatReservationRequest) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseSeatReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseSeatReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseSeatReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatReservationResponse) Reset() {
	*x = ReleaseSeatReservationResponse{}
	mi := &file_venue_v1_venue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatReservationResponse) ProtoMessage() {}

func (x *ReleaseSeatReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSeatReservationResponse) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseSeatReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FinalizeSeatReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSeatReservationRequest) Reset() {
	*x = FinalizeSeatReservationRequest{}
	mi := &file_venue_v1_venue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSeatReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSeatReservationRequest) ProtoMessage() {}

func (x *FinalizeSeatReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSeatReservationRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSeatReservationRequest) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{7}
}

func (x *FinalizeSeatReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *FinalizeSeatReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type FinalizeSeatReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSeatReservationResponse) Reset() {
	*x = FinalizeSeatReservationResponse{}
	mi := &file_venue_v1_venue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSeatReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSeatReservationResponse) ProtoMessage() {}

func (x *FinalizeSeatReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSeatReservationResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSeatReservationResponse) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeSeatReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSeatingPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatingPlanRequest) Reset() {
	*x = GetSeatingPlanRequest{}
	mi := &file_venue_v1_venue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatingPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatingPlanRequest) ProtoMessage() {}

func (x *GetSeatingPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatingPlanRequest.ProtoReflect.Descriptor instead.
func (*GetSeatingPlanRequest) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{9}
}

func (x *GetSeatingPlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

type GetSeatingPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeatingPlanResponse) Reset() {
	*x = GetSeatingPlanResponse{}
	mi := &file_venue_v1_venue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeatingPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeatingPlanResponse) ProtoMessage() {}

func (x *GetSeatingPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_venue_v1_venue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeatingPlanResponse.ProtoReflect.Descriptor instead.
func (*GetSeatingPlanResponse) Descriptor() ([]byte, []int) {
	return file_venue_v1_venue_proto_rawDescGZIP(), []int{10}
}

func (x *GetSeatingPlanResponse) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *GetSeatingPlanResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GetSeatingPlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_venue_v1_venue_proto protoreflect.FileDescriptor

const file_venue_v1_venue_proto_rawDesc = "" +
	"\n" +
	"\x14venue/v1/venue.proto\x12\racme.venue.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\n" +
	"SeatDetail\x12\x17\n" +
	"\aseat_id\x18\x01 \x01(\tR\x06seatId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x02 \x01(\tR\tsectionId\x12\x1d\n" +
	"\n" +
	"seat_label\x18\x03 \x01(\tR\tseatLabel\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\"\xe5\x01\n" +
	"\x17ReserveHeldSeatsRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x19\n" +
	"\bseat_ids\x18\x05 \x03(\tR\aseatIds\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xbe\x01\n" +
	"\x18ReserveHeldSeatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12/\n" +
	"\x05seats\x18\x03 \x03(\v2\x19.acme.venue.v1.SeatDetailR\x05seats\x120\n" +
	"\x14unavailable_seat_ids\x18\x04 \x03(\tR\x12unavailableSeatIds\"\x89\x02\n" +
	"\x1bAutoAssignAndReserveRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x1d\n" +
	"\n" +
	"section_id\x18\x03 \x01(\tR\tsectionId\x12%\n" +
	"\x0ereservation_id\x18\x04 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x90\x01\n" +
	"\x1cAutoAssignAndReserveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12/\n" +
	"\x05seats\x18\x03 \x03(\v2\x19.acme.venue.v1.SeatDetailR\x05seats\"^\n" +
	"\x1dReleaseSeatReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\":\n" +
	"\x1eReleaseSeatReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x1eFinalizeSeatReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\";\n" +
	"\x1fFinalizeSeatReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetSeatingPlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\"f\n" +
	"\x16GetSeatingPlanResponse\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\xb4\x04\n" +
	"\fVenueService\x12c\n" +
	"\x10ReserveHeldSeats\x12&.acme.venue.v1.ReserveHeldSeatsRequest\x1a'.acme.venue.v1.ReserveHeldSeatsResponse\x12o\n" +
	"\x14AutoAssignAndReserve\x12*.acme.venue.v1.AutoAssignAndReserveRequest\x1a+.acme.venue.v1.AutoAssignAndReserveResponse\x12u\n" +
	"\x16ReleaseSeatReservation\x12,.acme.venue.v1.ReleaseSeatReservationRequest\x1a-.acme.venue.v1.ReleaseSeatReservationResponse\x12x\n" +
	"\x17FinalizeSeatReservation\x12-.acme.venue.v1.FinalizeSeatReservationRequest\x1a..acme.venue.v1.FinalizeSeatReservationResponse\x12]\n" +
	"\x0eGetSeatingPlan\x12$.acme.venue.v1.GetSeatingPlanRequest\x1a%.acme.venue.v1.GetSeatingPlanResponseB\xb3\x01\n" +
	"\x11com.acme.venue.v1B\n" +
	"VenueProtoP\x01Z<github.com/org/ticketing/libs/grpc-stubs/go/venue/v1;venuev1\xa2\x02\x03AVX\xaa\x02\rAcme.Venue.V1\xca\x02\rAcme\\Venue\\V1\xe2\x02\x19Acme\\Venue\\V1\\GPBMetadata\xea\x02\x0fAcme::Venue::V1b\x06proto3"

var (
	file_venue_v1_venue_proto_rawDescOnce sync.Once
	file_venue_v1_venue_proto_rawDescData []byte
)

func file_venue_v1_venue_proto_rawDescGZIP() []byte {
	file_venue_v1_venue_proto_rawDescOnce.Do(func() {
		file_venue_v1_venue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_venue_v1_venue_proto_rawDesc), len(file_venue_v1_venue_proto_rawDesc)))
	})
	return file_venue_v1_venue_proto_rawDescData
}

var file_venue_v1_venue_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_venue_v1_venue_proto_goTypes = []any{
	(*SeatDetail)(nil),                      // 0: acme.venue.v1.SeatDetail
	(*ReserveHeldSeatsRequest)(nil),         // 1: acme.venue.v1.ReserveHeldSeatsRequest
	(*ReserveHeldSeatsResponse)(nil),        // 2: acme.venue.v1.ReserveHeldSeatsResponse
	(*AutoAssignAndReserveRequest)(nil),     // 3: acme.venue.v1.AutoAssignAndReserveRequest
	(*AutoAssignAndReserveResponse)(nil),    // 4: acme.venue.v1.AutoAssignAndReserveResponse
	(*ReleaseSeatReservationRequest)(nil),   // 5: acme.venue.v1.ReleaseSeatReservationRequest
	(*ReleaseSeatReservationResponse)(nil),  // 6: acme.venue.v1.ReleaseSeatReservationResponse
	(*FinalizeSeatReservationRequest)(nil),  // 7: acme.venue.v1.FinalizeSeatReservationRequest
	(*FinalizeSeatReservationResponse)(nil), // 8: acme.venue.v1.FinalizeSeatReservationResponse
	(*GetSeatingPlanRequest)(nil),           // 9: acme.venue.v1.GetSeatingPlanRequest
	(*GetSeatingPlanResponse)(nil),          // 10: acme.venue.v1.GetSeatingPlanResponse
	(*timestamppb.Timestamp)(nil),           // 11: google.protobuf.Timestamp
}
var file_venue_v1_venue_proto_depIdxs = []int32{
	11, // 0: acme.venue.v1.ReserveHeldSeatsRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: acme.venue.v1.ReserveHeldSeatsResponse.seats:type_name -> acme.venue.v1.SeatDetail
	11, // 2: acme.venue.v1.AutoAssignAndReserveRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: acme.venue.v1.AutoAssignAndReserveResponse.seats:type_name -> acme.venue.v1.SeatDetail
	1,  // 4: acme.venue.v1.VenueService.ReserveHeldSeats:input_type -> acme.venue.v1.ReserveHeldSeatsRequest
	3,  // 5: acme.venue.v1.VenueService.AutoAssignAndReserve:input_type -> acme.venue.v1.AutoAssignAndReserveRequest
	5,  // 6: acme.venue.v1.VenueService.ReleaseSeatReservation:input_type -> acme.venue.v1.ReleaseSeatReservationRequest
	7,  // 7: acme.venue.v1.VenueService.FinalizeSeatReservation:input_type -> acme.venue.v1.FinalizeSeatReservationRequest
	9,  // 8: acme.venue.v1.VenueService.GetSeatingPlan:input_type -> acme.venue.v1.GetSeatingPlanRequest
	2,  // 9: acme.venue.v1.VenueService.ReserveHeldSeats:output_type -> acme.venue.v1.ReserveHeldSeatsResponse
	4,  // 10: acme.venue.v1.VenueService.AutoAssignAndReserve:output_type -> acme.venue.v1.AutoAssignAndReserveResponse
	6,  // 11: acme.venue.v1.VenueService.ReleaseSeatReservation:output_type -> acme.venue.v1.ReleaseSeatReservationResponse
	8,  // 12: acme.venue.v1.VenueService.FinalizeSeatReservation:output_type -> acme.venue.v1.FinalizeSeatReservationResponse
	10, // 13: acme.venue.v1.VenueService.GetSeatingPlan:output_type -> acme.venue.v1.GetSeatingPlanResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_venue_v1_venue_proto_init() }
func file_venue_v1_venue_proto_init() {
	if File_venue_v1_venue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_venue_v1_venue_proto_rawDesc), len(file_venue_v1_venue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_venue_v1_venue_proto_goTypes,
		DependencyIndexes: file_venue_v1_venue_proto_depIdxs,
		MessageInfos:      file_venue_v1_venue_proto_msgTypes,
	}.Build()
	File_venue_v1_venue_proto = out.File
	file_venue_v1_venue_proto_goTypes = nil
	file_venue_v1_venue_proto_depIdxs = nil
}
