apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "apollo-router.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apollo-router.labels" . | nindent 4 }}
data:
  router.yaml: |
    {{- .Files.Get "files/router.yaml" | nindent 4 }}
  supergraph.graphql: |
    {{- .Files.Get "files/supergraph.graphql" | nindent 4 }}
