// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tickets/v1/tickets.proto

package ticketsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketRequest) Reset() {
	*x = GetTicketRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketRequest) ProtoMessage() {}

func (x *GetTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketRequest.ProtoReflect.Descriptor instead.
func (*GetTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{0}
}

func (x *GetTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type GetTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"` // decimal string, e.g. "12.50" — avoids floating-point precision loss
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // deprecated: kept for rollout compatibility with legacy flow
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Quota         int32                  `protobuf:"varint,9,opt,name=quota,proto3" json:"quota,omitempty"`
	Reserved      int32                  `protobuf:"varint,10,opt,name=reserved,proto3" json:"reserved,omitempty"`
	Sold          int32                  `protobuf:"varint,11,opt,name=sold,proto3" json:"sold,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,12,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	SeatingPlanId string                 `protobuf:"bytes,13,opt,name=seating_plan_id,json=seatingPlanId,proto3" json:"seating_plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTicketResponse) Reset() {
	*x = GetTicketResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTicketResponse) ProtoMessage() {}

func (x *GetTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTicketResponse.ProtoReflect.Descriptor instead.
func (*GetTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{1}
}

func (x *GetTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GetTicketResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTicketResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetTicketResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTicketResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetTicketResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetTicketResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetTicketResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetTicketResponse) GetQuota() int32 {
	if x != nil {
		return x.Quota
	}
	return 0
}

func (x *GetTicketResponse) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *GetTicketResponse) GetSold() int32 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *GetTicketResponse) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

func (x *GetTicketResponse) GetSeatingPlanId() string {
	if x != nil {
		return x.SeatingPlanId
	}
	return ""
}

type ValidateTicketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketRequest) Reset() {
	*x = ValidateTicketRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketRequest) ProtoMessage() {}

func (x *ValidateTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketRequest.ProtoReflect.Descriptor instead.
func (*ValidateTicketRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTicketRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type ValidateTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Price         string                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"` // decimal string, e.g. "12.50" — avoids floating-point precision loss
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTicketResponse) Reset() {
	*x = ValidateTicketResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTicketResponse) ProtoMessage() {}

func (x *ValidateTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTicketResponse.ProtoReflect.Descriptor instead.
func (*ValidateTicketResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateTicketResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ValidateTicketResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ValidateTicketResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ValidateTicketResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ReserveQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveQuotaRequest) Reset() {
	*x = ReserveQuotaRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveQuotaRequest) ProtoMessage() {}

func (x *ReserveQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveQuotaRequest.ProtoReflect.Descriptor instead.
func (*ReserveQuotaRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{4}
}

func (x *ReserveQuotaRequest) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ReserveQuotaRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveQuotaRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveQuotaRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ReserveQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	TicketId      string                 `protobuf:"bytes,3,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Remaining     int32                  `protobuf:"varint,5,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Price         string                 `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	MaxPerUser    int32                  `protobuf:"varint,8,opt,name=max_per_user,json=maxPerUser,proto3" json:"max_per_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveQuotaResponse) Reset() {
	*x = ReserveQuotaResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveQuotaResponse) ProtoMessage() {}

func (x *ReserveQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveQuotaResponse.ProtoReflect.Descriptor instead.
func (*ReserveQuotaResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveQuotaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveQuotaResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveQuotaResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *ReserveQuotaResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveQuotaResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *ReserveQuotaResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ReserveQuotaResponse) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ReserveQuotaResponse) GetMaxPerUser() int32 {
	if x != nil {
		return x.MaxPerUser
	}
	return 0
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // CANCELLED | EXPIRED | COMPENSATION
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{6}
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Remaining     int32                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReleaseReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseReservationResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type FinalizeReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeReservationRequest) Reset() {
	*x = FinalizeReservationRequest{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeReservationRequest) ProtoMessage() {}

func (x *FinalizeReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeReservationRequest.ProtoReflect.Descriptor instead.
func (*FinalizeReservationRequest) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *FinalizeReservationRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type FinalizeReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeReservationResponse) Reset() {
	*x = FinalizeReservationResponse{}
	mi := &file_tickets_v1_tickets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeReservationResponse) ProtoMessage() {}

func (x *FinalizeReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickets_v1_tickets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeReservationResponse.ProtoReflect.Descriptor instead.
func (*FinalizeReservationResponse) Descriptor() ([]byte, []int) {
	return file_tickets_v1_tickets_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FinalizeReservationResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

var File_tickets_v1_tickets_proto protoreflect.FileDescriptor

const file_tickets_v1_tickets_proto_rawDesc = "" +
	"\n" +
	"\x18tickets/v1/tickets.proto\x12\x0facme.tickets.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x10GetTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"\xb0\x03\n" +
	"\x11GetTicketResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x19\n" +
	"\border_id\x18\x05 \x01(\tR\aorderId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05quota\x18\t \x01(\x05R\x05quota\x12\x1a\n" +
	"\breserved\x18\n" +
	" \x01(\x05R\breserved\x12\x12\n" +
	"\x04sold\x18\v \x01(\x05R\x04sold\x12 \n" +
	"\fmax_per_user\x18\f \x01(\x05R\n" +
	"maxPerUser\x12&\n" +
	"\x0fseating_plan_id\x18\r \x01(\tR\rseatingPlanId\"4\n" +
	"\x15ValidateTicketRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"\x7f\n" +
	"\x16ValidateTicketResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xc9\x01\n" +
	"\x13ReserveQuotaRequest\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xfc\x01\n" +
	"\x14ReserveQuotaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1b\n" +
	"\tticket_id\x18\x03 \x01(\tR\bticketId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tremaining\x18\x05 \x01(\x05R\tremaining\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\a \x01(\tR\x05price\x12 \n" +
	"\fmax_per_user\x18\b \x01(\x05R\n" +
	"maxPerUser\"Z\n" +
	"\x19ReleaseReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"{\n" +
	"\x1aReleaseReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x05R\tremaining\"^\n" +
	"\x1aFinalizeReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\"^\n" +
	"\x1bFinalizeReservationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId2\x90\x04\n" +
	"\rTicketService\x12R\n" +
	"\tGetTicket\x12!.acme.tickets.v1.GetTicketRequest\x1a\".acme.tickets.v1.GetTicketResponse\x12m\n" +
	"\x1aValidateTicketAvailability\x12&.acme.tickets.v1.ValidateTicketRequest\x1a'.acme.tickets.v1.ValidateTicketResponse\x12[\n" +
	"\fReserveQuota\x12$.acme.tickets.v1.ReserveQuotaRequest\x1a%.acme.tickets.v1.ReserveQuotaResponse\x12m\n" +
	"\x12ReleaseReservation\x12*.acme.tickets.v1.ReleaseReservationRequest\x1a+.acme.tickets.v1.ReleaseReservationResponse\x12p\n" +
	"\x13FinalizeReservation\x12+.acme.tickets.v1.FinalizeReservationRequest\x1a,.acme.tickets.v1.FinalizeReservationResponseB\xc3\x01\n" +
	"\x13com.acme.tickets.v1B\fTicketsProtoP\x01Z@github.com/org/ticketing/libs/grpc-stubs/go/tickets/v1;ticketsv1\xa2\x02\x03ATX\xaa\x02\x0fAcme.Tickets.V1\xca\x02\x0fAcme\\Tickets\\V1\xe2\x02\x1bAcme\\Tickets\\V1\\GPBMetadata\xea\x02\x11Acme::Tickets::V1b\x06proto3"

var (
	file_tickets_v1_tickets_proto_rawDescOnce sync.Once
	file_tickets_v1_tickets_proto_rawDescData []byte
)

func file_tickets_v1_tickets_proto_rawDescGZIP() []byte {
	file_tickets_v1_tickets_proto_rawDescOnce.Do(func() {
		file_tickets_v1_tickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tickets_v1_tickets_proto_rawDesc), len(file_tickets_v1_tickets_proto_rawDesc)))
	})
	return file_tickets_v1_tickets_proto_rawDescData
}

var file_tickets_v1_tickets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tickets_v1_tickets_proto_goTypes = []any{
	(*GetTicketRequest)(nil),            // 0: acme.tickets.v1.GetTicketRequest
	(*GetTicketResponse)(nil),           // 1: acme.tickets.v1.GetTicketResponse
	(*ValidateTicketRequest)(nil),       // 2: acme.tickets.v1.ValidateTicketRequest
	(*ValidateTicketResponse)(nil),      // 3: acme.tickets.v1.ValidateTicketResponse
	(*ReserveQuotaRequest)(nil),         // 4: acme.tickets.v1.ReserveQuotaRequest
	(*ReserveQuotaResponse)(nil),        // 5: acme.tickets.v1.ReserveQuotaResponse
	(*ReleaseReservationRequest)(nil),   // 6: acme.tickets.v1.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil),  // 7: acme.tickets.v1.ReleaseReservationResponse
	(*FinalizeReservationRequest)(nil),  // 8: acme.tickets.v1.FinalizeReservationRequest
	(*FinalizeReservationResponse)(nil), // 9: acme.tickets.v1.FinalizeReservationResponse
	(*timestamppb.Timestamp)(nil),       // 10: google.protobuf.Timestamp
}
var file_tickets_v1_tickets_proto_depIdxs = []int32{
	10, // 0: acme.tickets.v1.GetTicketResponse.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: acme.tickets.v1.GetTicketResponse.updated_at:type_name -> google.protobuf.Timestamp
	10, // 2: acme.tickets.v1.ReserveQuotaRequest.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 3: acme.tickets.v1.TicketService.GetTicket:input_type -> acme.tickets.v1.GetTicketRequest
	2,  // 4: acme.tickets.v1.TicketService.ValidateTicketAvailability:input_type -> acme.tickets.v1.ValidateTicketRequest
	4,  // 5: acme.tickets.v1.TicketService.ReserveQuota:input_type -> acme.tickets.v1.ReserveQuotaRequest
	6,  // 6: acme.tickets.v1.TicketService.ReleaseReservation:input_type -> acme.tickets.v1.ReleaseReservationRequest
	8,  // 7: acme.tickets.v1.TicketService.FinalizeReservation:input_type -> acme.tickets.v1.FinalizeReservationRequest
	1,  // 8: acme.tickets.v1.TicketService.GetTicket:output_type -> acme.tickets.v1.GetTicketResponse
	3,  // 9: acme.tickets.v1.TicketService.ValidateTicketAvailability:output_type -> acme.tickets.v1.ValidateTicketResponse
	5,  // 10: acme.tickets.v1.TicketService.ReserveQuota:output_type -> acme.tickets.v1.ReserveQuotaResponse
	7,  // 11: acme.tickets.v1.TicketService.ReleaseReservation:output_type -> acme.tickets.v1.ReleaseReservationResponse
	9,  // 12: acme.tickets.v1.TicketService.FinalizeReservation:output_type -> acme.tickets.v1.FinalizeReservationResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_tickets_v1_tickets_proto_init() }
func file_tickets_v1_tickets_proto_init() {
	if File_tickets_v1_tickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tickets_v1_tickets_proto_rawDesc), len(file_tickets_v1_tickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tickets_v1_tickets_proto_goTypes,
		DependencyIndexes: file_tickets_v1_tickets_proto_depIdxs,
		MessageInfos:      file_tickets_v1_tickets_proto_msgTypes,
	}.Build()
	File_tickets_v1_tickets_proto = out.File
	file_tickets_v1_tickets_proto_goTypes = nil
	file_tickets_v1_tickets_proto_depIdxs = nil
}
