package com.ticketing.orders.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "orders")
public class Order {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id = UUID.randomUUID();

    @Column(name = "user_id", nullable = false, updatable = false)
    private UUID userId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private OrderStatus status;

    @Column(name = "expires_at", nullable = false)
    private OffsetDateTime expiresAt;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "ticket_id", nullable = false, updatable = false)
    private OrderTicket ticket;

    /**
     * Reservation identifier generated by order-service before calling ReserveQuota on
     * ticket-service (GA path). Nullable for backward compatibility with orders that were
     * created via the legacy path before CP-05.
     */
    @Column(name = "reservation_id", nullable = true, updatable = false)
    private UUID reservationId;

    /**
     * Number of units being purchased. Defaults to 1 (legacy path).
     */
    @Column(name = "quantity", nullable = false)
    private int quantity = 1;

    @Version
    @Column(nullable = false)
    private int version;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;

    @PrePersist
    void prePersist() {
        OffsetDateTime now = OffsetDateTime.now();
        this.createdAt = now;
        this.updatedAt = now;
    }

    @PreUpdate
    void preUpdate() {
        this.updatedAt = OffsetDateTime.now();
    }

    // ── constructors ───────────────────────────────────────────────────────────

    protected Order() {}

    public Order(UUID userId, OrderStatus status, OffsetDateTime expiresAt, OrderTicket ticket) {
        this.userId = userId;
        this.status = status;
        this.expiresAt = expiresAt;
        this.ticket = ticket;
    }

    public Order(UUID userId, OrderStatus status, OffsetDateTime expiresAt, OrderTicket ticket,
                 UUID reservationId, int quantity) {
        this.userId = userId;
        this.status = status;
        this.expiresAt = expiresAt;
        this.ticket = ticket;
        this.reservationId = reservationId;
        this.quantity = quantity;
    }

    // ── accessors ─────────────────────────────────────────────────────────────

    public UUID getId() { return id; }
    public UUID getUserId() { return userId; }
    public OrderStatus getStatus() { return status; }
    public void setStatus(OrderStatus status) { this.status = status; }
    public OffsetDateTime getExpiresAt() { return expiresAt; }
    public OrderTicket getTicket() { return ticket; }
    public UUID getReservationId() { return reservationId; }
    public int getQuantity() { return quantity; }
    public int getVersion() { return version; }
    public OffsetDateTime getCreatedAt() { return createdAt; }
    public OffsetDateTime getUpdatedAt() { return updatedAt; }

    /** True when this order is in a state that allows payment (CREATED or AWAITING_PAYMENT).
     *
     * AWAITING_PAYMENT is a UI display state; there is no production producer that
     * transitions orders into it before payment capture.  The real state machine is:
     *   CREATED → COMPLETE  (payment captured)
     *   CREATED → CANCELLED (expiration or user cancel)
     * Accepting CREATED here keeps this method consistent with the client's canPay
     * logic (order.status === "awaiting_payment" || order.status === "created").
     */
    public boolean isAwaitingPayment() {
        return this.status == OrderStatus.AWAITING_PAYMENT || this.status == OrderStatus.CREATED;
    }

    /** True when the order is in a terminal state. */
    public boolean isTerminal() {
        return this.status == OrderStatus.COMPLETE || this.status == OrderStatus.CANCELLED;
    }
}
