package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"

	"github.com/acme/venue-service/internal/repository"
)

// FindSeatingPlanByID is the resolver for the findSeatingPlanByID field.
func (r *entityResolver) FindSeatingPlanByID(ctx context.Context, id string) (*SeatingPlan, error) {
	plan, err := r.PlanRepo.FindByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrPlanNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapPlanToGQL(plan, nil), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
