// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreatePriceTierInput struct {
	Name  string `json:"name"`
	Price string `json:"price"`
}

type CreateSeatingPlanInput struct {
	VenueID          string         `json:"venueId"`
	TicketID         string         `json:"ticketId"`
	Name             string         `json:"name"`
	MaxSeatsPerOrder *int           `json:"maxSeatsPerOrder,omitempty"`
	AssignmentMode   AssignmentMode `json:"assignmentMode"`
	PricingMode      *string        `json:"pricingMode,omitempty"`
}

type CreateSectionInput struct {
	Name         string      `json:"name"`
	Type         SectionType `json:"type"`
	RowCount     *int        `json:"rowCount,omitempty"`
	ColumnCount  int         `json:"columnCount"`
	DisplayOrder *int        `json:"displayOrder,omitempty"`
}

type CreateVenueInput struct {
	Name     string  `json:"name"`
	Capacity int     `json:"capacity"`
	Timezone string  `json:"timezone"`
	Address  *string `json:"address,omitempty"`
}

type Mutation struct {
}

type PriceTier struct {
	ID     string `json:"id"`
	PlanID string `json:"planId"`
	Name   string `json:"name"`
	Price  string `json:"price"`
}

type Query struct {
}

type Seat struct {
	ID     string     `json:"id"`
	Label  string     `json:"label"`
	Price  int        `json:"price"`
	Status SeatStatus `json:"status"`
}

type SeatHoldResult struct {
	Held      []string `json:"held"`
	ExpiresAt string   `json:"expiresAt"`
}

type SeatingPlan struct {
	ID             string         `json:"id"`
	Sections       []*Section     `json:"sections"`
	AssignmentMode AssignmentMode `json:"assignmentMode"`
	Status         PlanStatus     `json:"status"`
}

func (SeatingPlan) IsEntity() {}

type Section struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Seats          []*Seat `json:"seats"`
	AvailableSeats int     `json:"availableSeats"`
}

type UpdateSeatingPlanInput struct {
	Name             *string         `json:"name,omitempty"`
	MaxSeatsPerOrder *int            `json:"maxSeatsPerOrder,omitempty"`
	AssignmentMode   *AssignmentMode `json:"assignmentMode,omitempty"`
	PricingMode      *string         `json:"pricingMode,omitempty"`
}

type UpdateSectionInput struct {
	Name         *string `json:"name,omitempty"`
	RowCount     *int    `json:"rowCount,omitempty"`
	ColumnCount  *int    `json:"columnCount,omitempty"`
	DisplayOrder *int    `json:"displayOrder,omitempty"`
}

type UpdateVenueInput struct {
	Name     string  `json:"name"`
	Capacity int     `json:"capacity"`
	Timezone string  `json:"timezone"`
	Address  *string `json:"address,omitempty"`
}

type Venue struct {
	ID          string `json:"id"`
	OrganizerID string `json:"organizerId"`
	Name        string `json:"name"`
	Capacity    int    `json:"capacity"`
	Timezone    string `json:"timezone"`
	Address     string `json:"address"`
}

type VenueSection struct {
	ID           string      `json:"id"`
	VenueID      string      `json:"venueId"`
	Name         string      `json:"name"`
	Type         SectionType `json:"type"`
	RowCount     int         `json:"rowCount"`
	ColumnCount  int         `json:"columnCount"`
	DisplayOrder int         `json:"displayOrder"`
	Capacity     int         `json:"capacity"`
}

type AssignmentMode string

const (
	AssignmentModeManual AssignmentMode = "MANUAL"
	AssignmentModeAuto   AssignmentMode = "AUTO"
)

var AllAssignmentMode = []AssignmentMode{
	AssignmentModeManual,
	AssignmentModeAuto,
}

func (e AssignmentMode) IsValid() bool {
	switch e {
	case AssignmentModeManual, AssignmentModeAuto:
		return true
	}
	return false
}

func (e AssignmentMode) String() string {
	return string(e)
}

func (e *AssignmentMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssignmentMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssignmentMode", str)
	}
	return nil
}

func (e AssignmentMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssignmentMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssignmentMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PlanStatus string

const (
	PlanStatusDraft    PlanStatus = "DRAFT"
	PlanStatusActive   PlanStatus = "ACTIVE"
	PlanStatusArchived PlanStatus = "ARCHIVED"
)

var AllPlanStatus = []PlanStatus{
	PlanStatusDraft,
	PlanStatusActive,
	PlanStatusArchived,
}

func (e PlanStatus) IsValid() bool {
	switch e {
	case PlanStatusDraft, PlanStatusActive, PlanStatusArchived:
		return true
	}
	return false
}

func (e PlanStatus) String() string {
	return string(e)
}

func (e *PlanStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PlanStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PlanStatus", str)
	}
	return nil
}

func (e PlanStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PlanStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PlanStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SeatStatus string

const (
	SeatStatusAvailable SeatStatus = "AVAILABLE"
	SeatStatusHeld      SeatStatus = "HELD"
	SeatStatusSold      SeatStatus = "SOLD"
)

var AllSeatStatus = []SeatStatus{
	SeatStatusAvailable,
	SeatStatusHeld,
	SeatStatusSold,
}

func (e SeatStatus) IsValid() bool {
	switch e {
	case SeatStatusAvailable, SeatStatusHeld, SeatStatusSold:
		return true
	}
	return false
}

func (e SeatStatus) String() string {
	return string(e)
}

func (e *SeatStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SeatStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SeatStatus", str)
	}
	return nil
}

func (e SeatStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SeatStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SeatStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SectionType string

const (
	SectionTypeSeated SectionType = "SEATED"
	SectionTypeGa     SectionType = "GA"
)

var AllSectionType = []SectionType{
	SectionTypeSeated,
	SectionTypeGa,
}

func (e SectionType) IsValid() bool {
	switch e {
	case SectionTypeSeated, SectionTypeGa:
		return true
	}
	return false
}

func (e SectionType) String() string {
	return string(e)
}

func (e *SectionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SectionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SectionType", str)
	}
	return nil
}

func (e SectionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SectionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SectionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
