package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"

	"github.com/acme/venue-service/internal/repository"
)

// SeatingPlan is the resolver for the seatingPlan field.
func (r *queryResolver) SeatingPlan(ctx context.Context, id string) (*SeatingPlan, error) {
	plan, err := r.PlanRepo.FindByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrPlanNotFound) {
			return nil, nil
		}
		return nil, err
	}
	sections, err := loadSections(ctx, r.SectionRepo, plan.ID)
	if err != nil {
		return nil, err
	}
	return mapPlanToGQL(plan, sections), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
