apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-grafana-provisioning
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  datasources.yml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "observability.fullname" . }}-prometheus:9090
        isDefault: true
        editable: false
