apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-grafana-provisioning
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  datasources.yml: |-
{{ .Files.Get "grafana/provisioning/datasources/datasources.yml" | replace "http://prometheus:9090" (printf "http://%s-prometheus:9090" (include "observability.fullname" .)) | replace "http://jaeger:16686" (printf "http://%s-jaeger:16686" (include "observability.fullname" .)) | indent 4 }}
