apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-prometheus-rules
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
{{- range $name, $content := .Values.prometheus.ruleFiles }}
  {{ $name }}: |-
{{ $content | indent 4 }}
{{- end }}