apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-prometheus-config
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  prometheus.yml: |-
{{ tpl .Values.prometheus.config . | indent 4 }}
