apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-otel-config
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
data:
  otel-collector.yaml: |-
{{ tpl .Values.otelCollector.config . | indent 4 }}
