apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability.fullname" . }}-otel-collector
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "observability.fullname" . }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "observability.fullname" . }}
        app.kubernetes.io/component: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: {{ printf "%s:%s" .Values.otelCollector.image.repository .Values.otelCollector.image.tag | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.otelCollector.service.grpcPort }}
            - name: otlp-http
              containerPort: {{ .Values.otelCollector.service.httpPort }}
            - name: metrics
              containerPort: {{ .Values.otelCollector.service.metricsPort }}
          command:
            - "/otelcol-contrib"
            - "--config=/etc/otelcol-contrib/config.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol-contrib
          resources:
            requests:
              cpu: {{ .Values.otelCollector.resources.requests.cpu }}
              memory: {{ .Values.otelCollector.resources.requests.memory }}
            limits:
              cpu: {{ .Values.otelCollector.resources.limits.cpu }}
              memory: {{ .Values.otelCollector.resources.limits.memory }}
      volumes:
        - name: config
          configMap:
            name: {{ include "observability.fullname" . }}-otel-config
