apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-jaeger
  labels:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.jaeger.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "observability.fullname" . }}
    app.kubernetes.io/component: jaeger
  ports:
    - name: ui
      port: {{ .Values.jaeger.service.uiPort }}
      targetPort: {{ .Values.jaeger.service.uiPort }}
    - name: otlp-grpc
      port: {{ .Values.jaeger.service.otlpPort }}
      targetPort: {{ .Values.jaeger.service.otlpPort }}
