supergraph:
  listen: 0.0.0.0:4001
  path: /graphql
  introspection: false

limits:
  max_depth: 15
  max_height: 200
  max_aliases: 30
  max_root_fields: 20

headers:
  all:
    request:
      - propagate:
          named: x-user-id
      - propagate:
          named: x-user-roles
      - propagate:
          named: x-user-id-sig
      - propagate:
          named: traceparent
      - propagate:
          named: tracestate

