-- V2__add_reservation_fields.sql
-- CP-05: Add reservation_id and quantity to orders table.
--
-- reservation_id: the UUID generated by order-service before calling ReserveQuota
--   on ticket-service. Nullable for backward compatibility with orders created
--   before this migration (legacy path). NOT NULL will be enforced at the
--   application layer for all new GA-path orders.
--
-- quantity: how many seats / units the user is purchasing. Defaults to 1 so that
--   existing rows remain valid after the migration runs.
--
-- Both columns are additive — no existing row is dropped or modified beyond
--   the DEFAULT backfill, which is safe for a live migration.

ALTER TABLE orders
    ADD COLUMN reservation_id UUID        NULL,
    ADD COLUMN quantity       INT         NOT NULL DEFAULT 1;

-- Index for lookups by reservation_id (used by compensation and reconciliation).
CREATE INDEX idx_orders_reservation_id ON orders(reservation_id) WHERE reservation_id IS NOT NULL;

-- Named check constraint: quantity must be at least 1.
ALTER TABLE orders
    ADD CONSTRAINT ck_orders_quantity_positive CHECK (quantity >= 1);
