package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/acme/attendance-service/internal/repository"
)

// FindAdmissionPassByID is the resolver for the findAdmissionPassByID field.
// Used by Apollo Router for entity resolution.
func (r *entityResolver) FindAdmissionPassByID(ctx context.Context, id string) (*AdmissionPass, error) {
	cred, err := r.Svc.GetAdmissionPassByCredentialID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	transfer, _ := r.Svc.FindLatestTransferByCredentialID(ctx, cred.ID)
	return mapCredentialToGQL(cred, transfer), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
