// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AdmissionPass struct {
	ID       string           `json:"id"`
	TicketID string           `json:"ticketId"`
	OrderID  string           `json:"orderId"`
	EventID  string           `json:"eventId"`
	Status   CredentialStatus `json:"status"`
	IssuedAt string           `json:"issuedAt"`
	UsedAt   *string          `json:"usedAt,omitempty"`
}

func (AdmissionPass) IsEntity() {}

type AttendancePolicy struct {
	EventID             string `json:"eventId"`
	RequireQRForEntry   bool   `json:"requireQrForEntry"`
	AllowManualOverride bool   `json:"allowManualOverride"`
}

type AttendanceSummary struct {
	EventID        string `json:"eventId"`
	TotalAdmitted  int    `json:"totalAdmitted"`
	TotalDenied    int    `json:"totalDenied"`
	TotalCheckedIn int    `json:"totalCheckedIn"`
}

type Query struct {
}

type CredentialStatus string

const (
	CredentialStatusIssued  CredentialStatus = "ISSUED"
	CredentialStatusUsed    CredentialStatus = "USED"
	CredentialStatusRevoked CredentialStatus = "REVOKED"
	CredentialStatusExpired CredentialStatus = "EXPIRED"
)

var AllCredentialStatus = []CredentialStatus{
	CredentialStatusIssued,
	CredentialStatusUsed,
	CredentialStatusRevoked,
	CredentialStatusExpired,
}

func (e CredentialStatus) IsValid() bool {
	switch e {
	case CredentialStatusIssued, CredentialStatusUsed, CredentialStatusRevoked, CredentialStatusExpired:
		return true
	}
	return false
}

func (e CredentialStatus) String() string {
	return string(e)
}

func (e *CredentialStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CredentialStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CredentialStatus", str)
	}
	return nil
}

func (e CredentialStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CredentialStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CredentialStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
