package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/acme/attendance-service/internal/repository"
)

// AdmissionPass is the resolver for the admissionPass field.
func (r *queryResolver) AdmissionPass(ctx context.Context, ticketID string, orderID *string) (*AdmissionPass, error) {
	cred, err := r.Svc.GetAdmissionPass(ctx, ticketID, orderID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapCredentialToGQL(cred), nil
}

// AttendancePolicy is the resolver for the attendancePolicy field.
func (r *queryResolver) AttendancePolicy(ctx context.Context, eventID string) (*AttendancePolicy, error) {
	policy, err := r.Svc.GetAttendancePolicy(ctx, eventID)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &AttendancePolicy{
		EventID:             policy.EventID,
		RequireQRForEntry:   policy.RequireQRForEntry,
		AllowManualOverride: policy.AllowManualOverride,
	}, nil
}

// AttendanceSummary is the resolver for the attendanceSummary field.
func (r *queryResolver) AttendanceSummary(ctx context.Context, eventID string) (*AttendanceSummary, error) {
	summary, err := r.Svc.GetAttendanceSummary(ctx, eventID)
	if err != nil {
		return nil, err
	}
	return &AttendanceSummary{
		EventID:        summary.EventID,
		TotalAdmitted:  summary.TotalAdmitted,
		TotalDenied:    summary.TotalDenied,
		TotalCheckedIn: summary.TotalCheckedIn,
	}, nil
}

// mapCredentialToGQL converts a domain AdmissionCredential to the GraphQL model.
func mapCredentialToGQL(c *repository.AdmissionCredential) *AdmissionPass {
	ap := &AdmissionPass{
		ID:       c.ID,
		TicketID: c.TicketID,
		OrderID:  c.OrderID,
		EventID:  c.EventID,
		Status:   CredentialStatus(c.Status),
		IssuedAt: c.IssuedAt.Format("2006-01-02T15:04:05Z07:00"),
	}
	if c.UsedAt != nil {
		usedAt := c.UsedAt.Format("2006-01-02T15:04:05Z07:00")
		ap.UsedAt = &usedAt
	}
	return ap
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
