-- Down migration for 005: no-op
--
-- The up migration only deactivates orphaned plans (a data-only change) and does
-- not alter the schema, so there is nothing to revert structurally.
-- Re-activating plans is intentionally not automated — an operator can manually
-- reactivate specific plans if needed after a rollback.
